# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-05-30 16:08:59
Modified by Robert Kearney on : 2021-05-30

This python script identifies areas that have the optimal climate and soil conditions for growing Sweet Corn. 
Crop climate and soil parameters for sweet corn are from the U.N. Food and Agriculture Organization(FAO).
Data for this analysis includes PRISM 30-Year Climate Normals (https://prism.oregonstate.edu/normals/) and 
SoilGrid Soil Ph (https://soilgrids.org/). The optimal suitabily constraints considered are annual precipita-
tion, mean temperature in the growing season months (May, June, July, and August), minumum temperature in 
April, and soil ph. The code defines the CornSuitability() function and then calls it. Each suitability con-
straint image is created by reclassifying the input data to create a boolean image for suitability (0 is un-
suitable and 1 is suitable). The final suitability is created by using Fuzzy logic and the "AND" operator to 
identify areas that meet all the optimal suitability constraints. 

"""

import arcpy
from arcpy.sa import *

def CornSuitability():  # Optimal Corn Suitability Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    results_folder = "C:\\Users\\Rkear\\OneDrive\\Documents\\PythonForGIS\\final\\Results"
    data_folder = "C:\\Users\\Rkear\\OneDrive\\Documents\\PythonForGIS\\final\\testdata"

    # Model Environment settings
    with arcpy.EnvManager(cellSize="MINOF", scratchWorkspace= results_folder, workspace= results_folder):
        PRISM_ppt_annual_clip_tif = arcpy.Raster(data_folder + "\\PRISM_ppt_annual_clip.tif")
        PRISM_tmean_05_clip_tif = arcpy.Raster(data_folder + "\\PRISM_tmean_05_clip.tif")
        PRISM_tmean_06_clip_tif = arcpy.Raster(data_folder + "\\PRISM_tmean_06_clip.tif")
        PRISM_tmean_07_clip_tif = arcpy.Raster(data_folder + "\\PRISM_tmean_07_clip.tif")
        PRISM_tmean_08_clip_tif = arcpy.Raster(data_folder + "\\PRISM_tmean_08_clip.tif")
        PRISM_tmin_04_clip_tif = arcpy.Raster(data_folder + "\\PRISM_tmin_04_clip.tif")
        SoilGrids_clip_tif = arcpy.Raster(data_folder + "\\SoilGrids_clip.tif")

        # Reclassify Annual Precipitation
        op_suit_ppt_tif = results_folder + "\\op_suit_ppt.tif"
        reclassify_ppt = op_suit_ppt_tif
        op_suit_ppt_tif = arcpy.sa.Reclassify(in_raster=PRISM_ppt_annual_clip_tif, reclass_field="VALUE", remap="0 799.99 0;800 1500 1;1500.01 6000 0", missing_values="DATA")
        op_suit_ppt_tif.save(reclassify_ppt)


        # Reclassify Mean Temperature: May
        op_suit_tmean_05_tif = results_folder + "\\op_suit_tmean_05.tif"
        reclassify_tmean_05 = op_suit_tmean_05_tif
        op_suit_tmean_05_tif = arcpy.sa.Reclassify(in_raster=PRISM_tmean_05_clip_tif, reclass_field="VALUE", remap="0 15.999 0;16 24 1;24.001 100 0", missing_values="DATA")
        op_suit_tmean_05_tif.save(reclassify_tmean_05)


        # Reclassify Mean Temperature: June
        op_suit_tmean_06_tif = results_folder + "\\op_suit_tmean_06.tif"
        reclassify_tmean_06 = op_suit_tmean_06_tif
        op_suit_tmean_06_tif = arcpy.sa.Reclassify(in_raster=PRISM_tmean_06_clip_tif, reclass_field="VALUE", remap="0 15.999 0;16 24 1;24.001 100 0", missing_values="DATA")
        op_suit_tmean_06_tif.save(reclassify_tmean_06)


        # Reclassify Mean Temperature: July
        op_suit_tmean_07_tif = results_folder + "\\op_suit_tmean_07.tif"
        reclassify_tmean_07 = op_suit_tmean_07_tif
        op_suit_tmean_07_tif = arcpy.sa.Reclassify(in_raster=PRISM_tmean_07_clip_tif, reclass_field="VALUE", remap="0 15.999 0;16 24 1;24.001 100 0", missing_values="NODATA")
        op_suit_tmean_07_tif.save(reclassify_tmean_07)


        # Reclassify Mean Temperature: August
        op_suit_tmean_08_tif = results_folder + "\\op_suit_tmean_08.tif"
        reclassify_tmean_08 = op_suit_tmean_08_tif
        op_suit_tmean_08_tif = arcpy.sa.Reclassify(in_raster=PRISM_tmean_08_clip_tif, reclass_field="VALUE", remap="0 15.999 0;16 24 1;24.001 100 0", missing_values="DATA")
        op_suit_tmean_08_tif.save(reclassify_tmean_08)


        # Reclassify Minimum Temperature: April
        op_suit_tmin_04_tif = results_folder + "\\op_suit_tmin_04.tif"
        reclassify_tmin_04 = op_suit_tmin_04_tif
        op_suit_tmin_04_tif = arcpy.sa.Reclassify(in_raster=PRISM_tmin_04_clip_tif, reclass_field="VALUE", remap="0 3.999 0;4 16 1", missing_values="DATA")
        op_suit_tmin_04_tif.save(reclassify_tmin_04)


        # Raster Calculator: SoilGrid divided by 10
        SoilGrid_10_tif = results_folder + "\\SoilGrid_10.tif"
        Raster_Calculator = SoilGrid_10_tif
        SoilGrid_10_tif =  SoilGrids_clip_tif / 10
        SoilGrid_10_tif.save(Raster_Calculator)


        # Reclassify Soil PH
        op_suit_soil_ph_tif = results_folder + "\\op_suit_soil_ph.tif"
        reclassify_soil_ph = op_suit_soil_ph_tif
        op_suit_soil_ph_tif = arcpy.sa.Reclassify(in_raster=SoilGrid_10_tif, reclass_field="VALUE", remap="0 5.499999 0;5.500000 6.800000 1;6.800001 7.200000 0", missing_values="DATA")
        op_suit_soil_ph_tif.save(reclassify_soil_ph)


        # Final Combined Suitability: Fuzzy Overlay (And)
        combined_op_suit_tif = results_folder + "\\combined_op_suit.tif"
        fuzzy_overlay = combined_op_suit_tif
        combined_op_suit_tif = arcpy.sa.FuzzyOverlay(in_rasters=[op_suit_ppt_tif, op_suit_tmean_05_tif, op_suit_tmean_06_tif, op_suit_tmean_07_tif, op_suit_tmean_08_tif, op_suit_tmin_04_tif, op_suit_soil_ph_tif], overlay_type="AND", gamma=0.9)
        combined_op_suit_tif.save(fuzzy_overlay)


CornSuitability()